parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  indent: [warn, tab]
  eol-last: [warn, always]
  linebreak-style: [warn, unix]
  curly: [warn, 'all']
  '@typescript-eslint/quotes': [warn, single]
  '@typescript-eslint/semi': [warn, always]
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-empty-function': off
