parser: '@typescript-eslint/parser'

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  '@typescript-eslint/semi': [error]
  quotes: [error, single]
  indent: [error, 2]
